#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) 1998 - 2021, Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
###########################################################################
language: c
os: linux
dist: bionic
cache:
  directories:
  - $HOME/wolfssl-4.7.0-stable
  - $HOME/mesalink-1.0.0
  - $HOME/bearssl-0.6

env:
  global:
  - LD_LIBRARY_PATH=/usr/local/lib

addons:
  apt: &common_apt
    config:
      retries: true
    packages: &common_packages
    - cmake
    - valgrind
    - libev-dev
    - libc-ares-dev
    - g++-8
    - stunnel4
    - libidn2-dev
    - gnutls-bin
    - python-impacket
    - ninja-build
    - libgsasl7-dev
    - libnghttp2-dev

jobs:
  include:
  - env:
    - T=debug C="--with-openssl" TFLAGS=-n
    - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
    arch: ppc64le
    addons:
      apt:
        <<: *common_apt
        packages:
        - *common_packages
        - libpsl-dev
        - libbrotli-dev
        - libzstd-dev
        - libev-dev
        - libssl-dev
        - libtool
        - pkg-config
        - zlib1g-dev

  - env:
    - T=debug C="--with-openssl" TFLAGS=-n
    - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
    arch: s390x
    addons:
      apt:
        <<: *common_apt
        packages:
        - *common_packages
        - libpsl-dev
        - libbrotli-dev
        - libzstd-dev
        - libev-dev
        - libssl-dev
        - libtool
        - pkg-config
        - zlib1g-dev

before_install:
- export "${OVERRIDE_CC-blank=}"
- export "${OVERRIDE_CXX-blank=}"

install:
- if [ "$T" = "coverage" ]; then pip2 install --user cpp-coveralls; fi

# before_script and script:
# Travis isn't reliable catching errors in inline script commands (#3730).
# Do not add anything here, instead add to the respective script.
before_script:
- ./scripts/travis/before_script.sh || travis_terminate 1
script:
- ./scripts/travis/script.sh || travis_terminate 1

# select branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master
  - /\/ci$/

notifications:
  email: false