# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  configure:
    steps:
      - run:
          command: |
            ./buildconf
            ./configure --enable-warnings --enable-werror --with-openssl

  build:
    steps:
      - run: make

  test:
    steps:
      - run: make test-nonflaky

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01

jobs:
  basic:
    executor: ubuntu
    steps:
      - checkout
      - configure
      - build
      - test

  arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - configure
      - build
      - test

workflows:
  x86-openssl:
    jobs:
      - basic

  arm-openssl:
    jobs:
      - arm
